import Navbar from "@/components/Navbar";
import "./globals.css";

export const metadata = {
    title: "My Portfolio",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="zh-TW">
            <body className="bg-gray-50 text-gray-900">
                {/* 1. 導覽列固定在最上方 */}
                <Navbar />

                {/* 2. 中間動態變化的頁面內容 */}
                <main>{children}</main>

                {/* 3. 順便寫個簡單的 Footer 頁尾 */}
                <footer className="py-6 text-center text-sm text-gray-400">
                    © {new Date().getFullYear()} Sutsanyuan. All rights reserved.
                </footer>
            </body>
        </html>
    );
}
